spring:
  application:
    name: video-comporess
  messages:
    encoding: UTF-8
    basename: i18n/messages
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true


  datasource:
    username: admin
    password: 123456
    url: jdbc:sqlite:./pro.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      # 初始化表
      schema-locations: classpath:schema.sql
      mode: always
  web:
    resources:
      static-locations: "classpath:/dist"


mybatis-plus:
  global-config:
    banner: off
    db-config:
      # logic-delete-field是entity的属性名
      logic-delete-field: deleteFlag
      # 1 代表已删除，不配置默认是1
      logic-delete-value: 1
      # 0 代表未删除，不配置默认是0
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# [可选] 日志配置, 一般不需要改
logging:
  config: classpath:logback-spring.xml

#ffmpegCommand: "ffmpeg -i {input_file} -b:v {videoBitrate} -bufsize 1000k  {output_file}"

#--------renren配置
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8080
  servlet:
#    context-path: /api
    session:
      cookie:
        http-only: true

knife4j:
  enable: true
  basic:
    enable: false
    username: admin
    password: admin
  setting:
    enableFooter: false



# 是否开启redis缓存  true开启   false关闭
renren:
  redis:
    open: false

#mybatis


