spring:
  application:
    name: video-comporess
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  datasource:
    username: admin
    password: 123456
    url: jdbc:sqlite:./pro.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      # 初始化表
      schema-locations: classpath:schema.sql
      mode: always


mybatis-plus:
  global-config:
    banner: off
    db-config:
      # logic-delete-field是entity的属性名
      logic-delete-field: deleteFlag
      # 1 代表已删除，不配置默认是1
      logic-delete-value: 1
      # 0 代表未删除，不配置默认是0
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



server:
  port: 8070

# [可选] 日志配置, 一般不需要改
logging:
  config: classpath:logback-spring.xml

#转换的文件路径
fileDirectory: "D:\\BaiduNetdiskDownload"

